-- Script d'initialisation Oracle pour CNSS Coopération Technique
-- À exécuter avec: sqlplus sys/admin123@//localhost:1521/XEPDB1 as sysdba @init.sql

-- Créer utilisateur COPT
CREATE USER COPT IDENTIFIED BY copt123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- Accorder privilèges
GRANT CONNECT, RESOURCE TO COPT;
GRANT CREATE SESSION TO COPT;
GRANT CREATE TABLE TO COPT;
GRANT CREATE VIEW TO COPT;
GRANT CREATE SEQUENCE TO COPT;
GRANT CREATE TRIGGER TO COPT;

-- Se connecter en tant que COPT
CONNECT COPT/copt123@//localhost:1521/XEPDB1;

-- Créer les séquences
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DOSSIER_COP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SALAIRE_ETR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AFFILIATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DEBIT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;

-- Table APP_USER
CREATE TABLE APP_USER (
    USER_ID NUMBER(10) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    ROLE VARCHAR2(20) NOT NULL,
    BUREAU_CODE VARCHAR2(10),
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table DOSSIER_COP
CREATE TABLE DOSSIER_COP (
    DCO_ID NUMBER(10) PRIMARY KEY,
    EMP_MAT NUMBER(8) NOT NULL,
    EMP_CLE NUMBER(2),
    NUM_AFFILIATION VARCHAR2(20) UNIQUE,
    NOM_PRENOM VARCHAR2(255),
    SITUATION VARCHAR2(20),
    DATE_EFFET DATE,
    DATE_ASSUJETTISSEMENT DATE,
    DATE_NAISSANCE DATE,
    DATE_DEPOT_CNSS DATE,
    MATRICULE_ENTREPRISE VARCHAR2(20),
    CODE_REGIME_COOP VARCHAR2(10),
    PAYS_DETACHEMENT VARCHAR2(100),
    PERIODE_DEBUT DATE,
    PERIODE_FIN DATE,
    SALAIRE_TRIMESTRE NUMBER(15,3),
    REGIME VARCHAR2(10),
    TYPE_COOPERATION VARCHAR2(50),
    ACTIF NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER(10)
);

-- Table SALAIRE_ETRANGER
CREATE TABLE SALAIRE_ETRANGER (
    SLE_ID NUMBER(10) PRIMARY KEY,
    EMP_MAT NUMBER(8) NOT NULL,
    EMP_CLE NUMBER(2),
    DCO_DTDEB DATE NOT NULL,
    SLE_DATE DATE NOT NULL,
    SLE_SALAIRE_DEVISE NUMBER(15,3),
    SLE_DEVISE VARCHAR2(3),
    SLE_TAUX_CHANGE NUMBER(10,6),
    SLE_SALAIRE NUMBER(15,3),
    SLE_SALAIRE_TRIM NUMBER(15,3),
    SLE_AGENT NUMBER(6),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- Table AFFILIATION
CREATE TABLE AFFILIATION (
    AFF_ID NUMBER(10) PRIMARY KEY,
    NUM_AFFILIATION VARCHAR2(20) UNIQUE,
    MATRICULE NUMBER(8),
    DATE_EFFET DATE,
    DATE_ASSUJETTISSEMENT DATE,
    REGIME VARCHAR2(10),
    ATTESTATION_PATH VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table DEBIT
CREATE TABLE DEBIT (
    DEB_ID NUMBER(10) PRIMARY KEY,
    NUM_AFFILIATION VARCHAR2(20),
    TRIMESTRE VARCHAR2(10),
    DATE_EFFET DATE,
    MONTANT_COTISATION NUMBER(15,3),
    PAYE NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table PAYMENT
CREATE TABLE PAYMENT (
    PAY_ID NUMBER(10) PRIMARY KEY,
    NUM_AFFILIATION VARCHAR2(20),
    TRIMESTRE VARCHAR2(10),
    MONTANT NUMBER(15,3),
    MODE_PAIEMENT VARCHAR2(50),
    PAIEMENT_PARTIEL NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index
CREATE INDEX IDX_DOSSIER_MAT ON DOSSIER_COP(EMP_MAT);
CREATE INDEX IDX_DOSSIER_REGIME ON DOSSIER_COP(REGIME);
CREATE INDEX IDX_SALAIRE_MAT ON SALAIRE_ETRANGER(EMP_MAT);
CREATE INDEX IDX_AFFILIATION_NUM ON AFFILIATION(NUM_AFFILIATION);
CREATE INDEX IDX_DEBIT_AFF ON DEBIT(NUM_AFFILIATION);
CREATE INDEX IDX_PAYMENT_AFF ON PAYMENT(NUM_AFFILIATION);

-- Données de test
-- Utilisateur admin par défaut (mot de passe: admin123)
INSERT INTO APP_USER (USER_ID, USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ROLE, BUREAU_CODE, ACTIVE)
VALUES (USER_SEQ.NEXTVAL, 'admin', '$2a$10$8ZqPPcT0rJw8JCVHcBCh1O4aJCxJxV5jGzqGZqHqv5sBqvY0Q1xiq', 
        'admin@cnss.tn', 'Admin', 'CNSS', 'ADMIN', 'TUNIS', 1);

INSERT INTO APP_USER (USER_ID, USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, ROLE, BUREAU_CODE, ACTIVE)
VALUES (USER_SEQ.NEXTVAL, 'agent', '$2a$10$8ZqPPcT0rJw8JCVHcBCh1O4aJCxJxV5jGzqGZqHqv5sBqvY0Q1xiq', 
        'agent@cnss.tn', 'Agent', 'Coop Tech', 'AGENT_COOP_TECH', 'TUNIS', 1);

COMMIT;

-- Afficher message de succès
SELECT 'Base de données CNSS Coopération Technique initialisée avec succès!' AS STATUS FROM DUAL;
