-- Script de création des tables GED pour Oracle
-- Exécuter ce script dans SQL Developer ou votre client Oracle

-- Séquence pour les IDs
CREATE SEQUENCE GED_DOC_SEQ START WITH 1 INCREMENT BY 1;

-- Table principale des documents
CREATE TABLE GED_DOCUMENTS (
    ID NUMBER(19) PRIMARY KEY,
    TITRE VARCHAR2(255) NOT NULL,
    DESCRIPTION CLOB,
    FICHIER_NOM VARCHAR2(255) NOT NULL,
    FICHIER_TYPE VARCHAR2(100) NOT NULL,
    FICHIER_TAILLE NUMBER(19),
    CHEMIN_FICHIER VARCHAR2(500) NOT NULL,
    CATEGORIE VARCHAR2(50) NOT NULL,
    CREE_PAR VARCHAR2(100) NOT NULL,
    DATE_CREATION TIMESTAMP NOT NULL,
    DATE_MODIFICATION TIMESTAMP
);

-- Table des tags associés aux documents
CREATE TABLE GED_DOCUMENT_TAGS (
    DOCUMENT_ID NUMBER(19) NOT NULL,
    TAG VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_GED_DOC_TAGS FOREIGN KEY (DOCUMENT_ID) REFERENCES GED_DOCUMENTS(ID)
);

-- Index pour améliorer les performances
CREATE INDEX IDX_GED_DOC_CATEGORIE ON GED_DOCUMENTS(CATEGORIE);
CREATE INDEX IDX_GED_DOC_TITRE ON GED_DOCUMENTS(TITRE);
CREATE INDEX IDX_GED_DOC_DATE ON GED_DOCUMENTS(DATE_CREATION);
