-- Script d'initialisation complet Oracle pour CNSS Coopération Technique
-- Création de l'utilisateur COPT
CREATE USER COPT IDENTIFIED BY copt123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- Accorder privilèges
GRANT CONNECT, RESOURCE TO COPT;
GRANT CREATE SESSION TO COPT;
GRANT CREATE TABLE TO COPT;
GRANT CREATE VIEW TO COPT;
GRANT CREATE SEQUENCE TO COPT;
GRANT CREATE TRIGGER TO COPT;
GRANT UNLIMITED TABLESPACE TO COPT;

COMMIT;

SELECT 'Utilisateur COPT créé avec succès' AS STATUS FROM DUAL;

EXIT;
