#!/bin/bash

echo "🚀 Démarrage des services en LOCAL (sans Docker)"
echo "================================================"
echo ""
echo "⚠️  IMPORTANT: Vous devez ouvrir 6 terminaux différents"
echo ""
echo "Terminal 1 - Eureka Server:"
echo "cd $(pwd)/eureka-server && mvn spring-boot:run"
echo ""
echo "Terminal 2 - Gateway Service (attendre 30s après Eureka):"
echo "cd $(pwd)/gateway-service && mvn spring-boot:run"
echo ""
echo "Terminal 3 - Auth Service:"
echo "cd $(pwd)/auth-service && mvn spring-boot:run"
echo ""
echo "Terminal 4 - Employer Service:"
echo "cd $(pwd)/employer-service && mvn spring-boot:run"
echo ""
echo "Terminal 5 - Affiliation Service:"
echo "cd $(pwd)/affiliation-service && mvn spring-boot:run"
echo ""
echo "Terminal 6 - Frontend Angular:"
echo "cd $(pwd)/frontend && npm start"
echo ""
echo "================================================"
echo "Ou utilisez tmux/screen pour tout lancer en même temps :"
echo ""
echo "tmux new-session -d -s cnss-backend 'cd $(pwd)/eureka-server && mvn spring-boot:run'"
echo "sleep 30"
echo "tmux new-window -t cnss-backend -n gateway 'cd $(pwd)/gateway-service && mvn spring-boot:run'"
echo "tmux new-window -t cnss-backend -n auth 'cd $(pwd)/auth-service && mvn spring-boot:run'"
echo "tmux new-window -t cnss-backend -n employer 'cd $(pwd)/employer-service && mvn spring-boot:run'"
echo "tmux new-window -t cnss-backend -n affiliation 'cd $(pwd)/affiliation-service && mvn spring-boot:run'"
echo "tmux new-window -t cnss-backend -n frontend 'cd $(pwd)/frontend && npm start'"
echo "tmux attach -t cnss-backend"
