-- Script pour ajouter les colonnes personnelles à la table DOSSIER_COP
-- À exécuter sur la base Oracle CNSS

-- Informations personnelles de l'assuré
ALTER TABLE COPT.DOSSIER_COP ADD (
    DATE_NAISSANCE DATE,
    LIEU_NAISSANCE VARCHAR2(100),
    SEXE VARCHAR2(1),
    NUM_PASSEPORT VARCHAR2(50),
    NUM_SECU_ORIGINE VARCHAR2(50),
    POSTE VARCHAR2(100),
    TYPE_CONTRAT VARCHAR2(20)
);

-- Coordonnées
ALTER TABLE COPT.DOSSIER_COP ADD (
    ADRESSE VARCHAR2(255),
    VILLE VARCHAR2(100),
    PAYS_RESIDENCE VARCHAR2(100),
    TELEPHONE VARCHAR2(20),
    EMAIL VARCHAR2(100)
);

-- Commentaires sur les colonnes
COMMENT ON COLUMN COPT.DOSSIER_COP.DATE_NAISSANCE IS 'Date de naissance de l''assuré';
COMMENT ON COLUMN COPT.DOSSIER_COP.LIEU_NAISSANCE IS 'Lieu de naissance de l''assuré';
COMMENT ON COLUMN COPT.DOSSIER_COP.SEXE IS 'Sexe: M=Masculin, F=Féminin';
COMMENT ON COLUMN COPT.DOSSIER_COP.NUM_PASSEPORT IS 'Numéro de passeport';
COMMENT ON COLUMN COPT.DOSSIER_COP.NUM_SECU_ORIGINE IS 'Numéro sécurité sociale du pays d''origine';
COMMENT ON COLUMN COPT.DOSSIER_COP.POSTE IS 'Poste occupé';
COMMENT ON COLUMN COPT.DOSSIER_COP.TYPE_CONTRAT IS 'Type de contrat: CDI, CDD, Stage, Autre';
COMMENT ON COLUMN COPT.DOSSIER_COP.ADRESSE IS 'Adresse de résidence';
COMMENT ON COLUMN COPT.DOSSIER_COP.VILLE IS 'Ville de résidence';
COMMENT ON COLUMN COPT.DOSSIER_COP.PAYS_RESIDENCE IS 'Pays de résidence';
COMMENT ON COLUMN COPT.DOSSIER_COP.TELEPHONE IS 'Numéro de téléphone';
COMMENT ON COLUMN COPT.DOSSIER_COP.EMAIL IS 'Adresse email';

COMMIT;
