-- ============================================================
-- Script SQL pour la table DOSSIER_ATCT
-- Module ATCT - Coopération Technique CNSS
-- ============================================================

-- Création du schéma si nécessaire
CREATE SCHEMA IF NOT EXISTS COPT;

-- Séquence pour l'auto-increment
CREATE SEQUENCE IF NOT EXISTS COPT.DOSSIER_ATCT_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Table principale DOSSIER_ATCT
CREATE TABLE IF NOT EXISTS COPT.DOSSIER_ATCT (
    -- Clé primaire
    ATCT_ID BIGINT PRIMARY KEY DEFAULT nextval('COPT.DOSSIER_ATCT_SEQ'),
    
    -- Informations Personnelles
    NUM_SECU_SOCIALE VARCHAR(20),
    NOM_FR VARCHAR(100) NOT NULL,
    PRENOM_FR VARCHAR(100) NOT NULL,
    NOM_AR VARCHAR(100),
    PRENOM_AR VARCHAR(100),
    DATE_NAISSANCE DATE,
    LIEU_NAISSANCE_FR VARCHAR(100),
    SEXE VARCHAR(1) CHECK (SEXE IN ('M', 'F')),
    NATIONALITE VARCHAR(50) DEFAULT 'Tunisienne',
    NUM_CIN VARCHAR(20),
    NUM_PASSEPORT VARCHAR(50),
    
    -- Adresse en Tunisie
    ADRESSE_TUNISIE VARCHAR(255),
    CODE_POSTAL_TUNISIE VARCHAR(10),
    VILLE_TUNISIE VARCHAR(100),
    
    -- Adresse à l'Étranger
    ADRESSE_ETRANGER VARCHAR(255),
    CODE_POSTAL_ETRANGER VARCHAR(20),
    VILLE_ETRANGER VARCHAR(100),
    PAYS_ETRANGER VARCHAR(100),
    PAYS_CODE INTEGER,
    
    -- Contact
    TELEPHONE VARCHAR(20),
    EMAIL VARCHAR(100) NOT NULL,
    
    -- Établissement d'Origine (Tunisie)
    ETABLISSEMENT_ORIGINE VARCHAR(200),
    MATRICULE_EMPLOYEUR BIGINT,
    CLE_EMPLOYEUR INTEGER,
    
    -- Mission / Organisme à l'Étranger
    ORGANISME_ETRANGER VARCHAR(200),
    MISSION_POSTE VARCHAR(200),
    
    -- Période de Détachement
    DATE_DEBUT_DETACHEMENT DATE NOT NULL,
    DATE_FIN_DETACHEMENT DATE,
    DATE_RENOUVELLEMENT DATE,
    
    -- Salaires
    SALAIRE_TUNISIE NUMERIC(15,3),
    SALAIRE_ETRANGER NUMERIC(15,3),
    DEVISE_ETRANGER VARCHAR(10),
    SALAIRE_CONVERTI_TND NUMERIC(15,3),
    
    -- Mode de Paiement
    MODE_PAIEMENT VARCHAR(20) DEFAULT 'TRIMESTRIEL' CHECK (MODE_PAIEMENT IN ('TRIMESTRIEL', 'ANNUEL', 'MENSUEL', 'ANTICIPE')),
    PAIEMENT_ANTICIPE BOOLEAN DEFAULT FALSE,
    
    -- Régime
    CODE_REGIME VARCHAR(10) DEFAULT '500' CHECK (CODE_REGIME IN ('500', '510', '515')),
    
    -- Options Assurance
    ASSURANCE_MALADIE BOOLEAN DEFAULT FALSE,
    CAPITAL_DECES BOOLEAN DEFAULT FALSE,
    DATE_EFFET_ASSURANCE DATE,
    
    -- Statut du Dossier
    STATUT VARCHAR(20) DEFAULT 'EN_ATTENTE' CHECK (STATUT IN ('EN_ATTENTE', 'VALIDE', 'REJETE', 'EN_COURS', 'AFFILIE')),
    DATE_VALIDATION TIMESTAMP,
    VALIDE_PAR BIGINT,
    MOTIF_REJET VARCHAR(500),
    
    -- Compte Coopérant (pour connexion)
    COMPTE_CREE BOOLEAN DEFAULT FALSE,
    MOT_PASSE_TEMP VARCHAR(100),
    DATE_ENVOI_EMAIL TIMESTAMP,
    EMAIL_ENVOYE BOOLEAN DEFAULT FALSE,
    
    -- Lien vers Affiliation
    AFFILIATION_ID BIGINT,
    NUM_AFFILIATION VARCHAR(20),
    
    -- Documents
    DOCUMENTS_DEPOSES BOOLEAN DEFAULT FALSE,
    DATE_DEPOT_DOCUMENTS TIMESTAMP,
    
    -- Audit
    CREE_PAR BIGINT,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIE_PAR BIGINT,
    DATE_MODIFICATION TIMESTAMP,
    ACTIF BOOLEAN DEFAULT TRUE
);

-- Index pour améliorer les performances
CREATE INDEX IF NOT EXISTS IDX_ATCT_EMAIL ON COPT.DOSSIER_ATCT(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_ATCT_NUM_SECU ON COPT.DOSSIER_ATCT(NUM_SECU_SOCIALE);
CREATE INDEX IF NOT EXISTS IDX_ATCT_STATUT ON COPT.DOSSIER_ATCT(STATUT);
CREATE INDEX IF NOT EXISTS IDX_ATCT_CODE_REGIME ON COPT.DOSSIER_ATCT(CODE_REGIME);
CREATE INDEX IF NOT EXISTS IDX_ATCT_DATE_CREATION ON COPT.DOSSIER_ATCT(DATE_CREATION DESC);
CREATE INDEX IF NOT EXISTS IDX_ATCT_PAYS_CODE ON COPT.DOSSIER_ATCT(PAYS_CODE);
CREATE INDEX IF NOT EXISTS IDX_ATCT_MATRICULE_EMP ON COPT.DOSSIER_ATCT(MATRICULE_EMPLOYEUR, CLE_EMPLOYEUR);
CREATE INDEX IF NOT EXISTS IDX_ATCT_ACTIF ON COPT.DOSSIER_ATCT(ACTIF);

-- Commentaires sur la table
COMMENT ON TABLE COPT.DOSSIER_ATCT IS 'Table des dossiers de coopération technique ATCT - تسوية فترات إلحاق في إطار التعاون الفني';
COMMENT ON COLUMN COPT.DOSSIER_ATCT.ATCT_ID IS 'Identifiant unique du dossier';
COMMENT ON COLUMN COPT.DOSSIER_ATCT.NUM_SECU_SOCIALE IS 'Numéro de sécurité sociale';
COMMENT ON COLUMN COPT.DOSSIER_ATCT.STATUT IS 'Statut du dossier: EN_ATTENTE, VALIDE, REJETE, EN_COURS, AFFILIE';
COMMENT ON COLUMN COPT.DOSSIER_ATCT.MODE_PAIEMENT IS 'Mode de paiement: TRIMESTRIEL, ANNUEL, MENSUEL, ANTICIPE';
COMMENT ON COLUMN COPT.DOSSIER_ATCT.CODE_REGIME IS 'Code régime: 500 (Général), 510 (Spécial), 515';

-- ============================================================
-- Données de test (optionnel)
-- ============================================================

-- INSERT INTO COPT.DOSSIER_ATCT (
--     NOM_FR, PRENOM_FR, NOM_AR, PRENOM_AR,
--     EMAIL, TELEPHONE,
--     ADRESSE_TUNISIE, VILLE_TUNISIE, CODE_POSTAL_TUNISIE,
--     PAYS_ETRANGER, PAYS_CODE,
--     DATE_DEBUT_DETACHEMENT,
--     SALAIRE_TUNISIE, SALAIRE_ETRANGER, DEVISE_ETRANGER,
--     CODE_REGIME, MODE_PAIEMENT,
--     CREE_PAR
-- ) VALUES (
--     'BEN SALAH', 'Mohamed', 'بن صالح', 'محمد',
--     'mohamed.bensalah@example.com', '+216 98 765 432',
--     '15 Rue de la Liberté', 'Tunis', '1000',
--     'Émirats Arabes Unis', 784,
--     '2025-01-01',
--     3500.000, 15000.00, 'AED',
--     '500', 'TRIMESTRIEL',
--     1
-- );

-- ============================================================
-- Vue pour le reporting
-- ============================================================

CREATE OR REPLACE VIEW COPT.V_DOSSIERS_ATCT_ACTIFS AS
SELECT 
    d.ATCT_ID,
    d.NUM_SECU_SOCIALE,
    d.NOM_FR || ' ' || d.PRENOM_FR AS NOM_COMPLET_FR,
    d.NOM_AR || ' ' || d.PRENOM_AR AS NOM_COMPLET_AR,
    d.EMAIL,
    d.TELEPHONE,
    d.PAYS_ETRANGER,
    d.DATE_DEBUT_DETACHEMENT,
    d.DATE_FIN_DETACHEMENT,
    d.SALAIRE_TUNISIE,
    d.CODE_REGIME,
    d.MODE_PAIEMENT,
    d.STATUT,
    d.DATE_CREATION,
    d.EMAIL_ENVOYE,
    d.NUM_AFFILIATION
FROM COPT.DOSSIER_ATCT d
WHERE d.ACTIF = TRUE
ORDER BY d.DATE_CREATION DESC;

COMMENT ON VIEW COPT.V_DOSSIERS_ATCT_ACTIFS IS 'Vue des dossiers ATCT actifs pour le reporting';
