-- Table EMPLOYEUR pour la gestion des employeurs
CREATE TABLE COPT.EMPLOYEUR (
    EMP_MAT NUMBER(10) NOT NULL,
    EMP_CLE NUMBER(2) NOT NULL,
    NOM_COMMERCIAL VARCHAR2(200),
    RAISON_SOCIALE VARCHAR2(200),
    REGIME VARCHAR2(10),
    PAYS VARCHAR2(100),
    ADRESSE VARCHAR2(500),
    TELEPHONE VARCHAR2(50),
    EMAIL VARCHAR2(100),
    STATUT VARCHAR2(20),
    DATE_CREATION DATE,
    CONSTRAINT PK_EMPLOYEUR PRIMARY KEY (EMP_MAT, EMP_CLE)
);

-- Insérer des employeurs de test
INSERT INTO COPT.EMPLOYEUR (EMP_MAT, EMP_CLE, NOM_COMMERCIAL, RAISON_SOCIALE, REGIME, PAYS, ADRESSE, TELEPHONE, EMAIL, STATUT, DATE_CREATION)
VALUES (500380, 54, 'Test Company France', 'Enterprise Test SARL', '500', 'France', '123 Rue de Paris', '+21671234567', 'contact@testcompany.fr', 'Actif', DATE '2024-01-15');

INSERT INTO COPT.EMPLOYEUR (EMP_MAT, EMP_CLE, NOM_COMMERCIAL, RAISON_SOCIALE, REGIME, PAYS, ADRESSE, TELEPHONE, EMAIL, STATUT, DATE_CREATION)
VALUES (510245, 2, 'IntCorp Deutschland', 'International Corporation GmbH', '510', 'Allemagne', '456 Berliner Strasse', '+21671234568', 'info@intcorp.de', 'Actif', DATE '2024-02-10');

INSERT INTO COPT.EMPLOYEUR (EMP_MAT, EMP_CLE, NOM_COMMERCIAL, RAISON_SOCIALE, REGIME, PAYS, ADRESSE, TELEPHONE, EMAIL, STATUT, DATE_CREATION)
VALUES (500380, 55, 'TechSol France', 'Tech Solutions SARL', '500', 'France', '789 Avenue des Champs', '+21671234569', 'contact@techsol.fr', 'Inactif', DATE '2023-12-01');

COMMIT;
