-- OTP reset password
-- Table: PASSWORD_RESET_OTP

CREATE TABLE COPT.PASSWORD_RESET_OTP (
    OTP_ID NUMBER(19,0) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL,
    OTP_CODE VARCHAR2(10) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED NUMBER(1,0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX COPT.IDX_PW_RESET_OTP_EMAIL ON COPT.PASSWORD_RESET_OTP (EMAIL);
CREATE INDEX COPT.IDX_PW_RESET_OTP_EMAIL_OTP ON COPT.PASSWORD_RESET_OTP (EMAIL, OTP_CODE);
